# general settings
name: UHDPromer-uhdblur

model_type: FeMaSRModel 
scale: &upscale 1
num_gpu: 2 # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: General_Image_Train
    type: PairedImageDataset
#    dataroot_gt: ../datasets/HQ_sub
    # type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/datasets/UHD-Blur/training_set/gt
    dataroot_lq: /root/autodl-tmp/datasets/UHD-Blur/training_set/input
#
    io_backend:
      type: disk

    gt_size: 512
    use_resize_crop: False
    use_flip: False
    use_rot: False

    # data loader
    use_shuffle: true
    geometric_augs: True
    batch_size_per_gpu: &bsz 10
    num_worker_per_gpu: *bsz
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz

  val:
    name: General_Image_Valid
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/datasets/UHD-Blur/training_set/gt
    dataroot_lq: /root/autodl-tmp/datasets/UHD-Blur/training_set/input
    gt_size: 512
    io_backend:
      type: disk
    geometric_augs: True
    use_resize_crop: False
    use_flip: False
    use_rot: False

# network structures
network_g:
  type: UHDPromer 
  gt_resolution: 512

#  channel_query_dict: {8: 256, 16: 256, 32: 256, 64: 128, 128: 64, 256: 32, 512: 32,}
  unit_num: 3  
  number_block: 5  
  num_heads: 8
  match_factor: 4
  ffn_expansion_factor: 4  
  scale_factor: 8
  bias: True
  LayerNorm_type: 'WithBias'
  attention_discrimination: True
  ffn_discrimination: True
  SR_Guidance: True
  ffn_restormer: False

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3

path:
#  pretrain_network_hq: /data_8T1/wangcong/net_g_260000.pth
#  pretrain_network_g: /data_8T1/wangcong/NeurIPS/335-DPT-base-dense/experiments/014_FeMaSR_LQ_stage/models/net_g_120000.pth
#  pretrain_network_d: ~
#  strict_load: false
#  resume_state: /data_8T1/wangcong/NeurIPS/335-DPT-base-dense/experiments/014_FeMaSR_LQ_stage/training_states/120000.state

  pretrain_network_hq: ~
  pretrain_network_g: ~
  pretrain_network_d: ~
  strict_load: false
  resume_state: ~


# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

#  scheduler:
#    type: MultiStepLR
#    # milestones: [50000, 100000, 200000, 300000]
#    # gamma: 1
#    milestones: [120000,150000,180000,210000]
#    gamma: 0.3 CosineAnnealingRestartLR
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [100, 500000]
    restart_weights: [1, 1]
    eta_mins: [0.0005, 0.0000001]

  total_iter: 502000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0 
    reduction: mean
  pixel_ssim_opt:
    loss_weight: !!float 0.25

  fft_opt:
    type: FFTLoss
    loss_weight: !!float 0.1


  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 0
    
  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 0

  codebook_opt:
    loss_weight: 0
  
  semantic_opt:
    loss_weight: 0

  net_d_iters: 0
  net_d_init_iters: !!float 0 

# validation settings·
val:
  val_freq: !!float 50000000000
  save_img: true

  key_metric: ssim
  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr 
      crop_border: 4
      test_y_channel: true
    ssim:
      type: ssim 
      crop_border: 4
      test_y_channel: true
    lpips:
      type: lpips 
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e9
  save_latest_freq: !!float 1e4
  show_tf_imgs_freq: !!float 5000
  use_tb_logger: true

# wandb:
    # project: ESRGAN
    # resume_id: ~

dist_params:
  backend: nccl
  port: 16500 
find_unused_parameters: true
